#!/usr/bin/env sh

main() {
    product=$1
    echo "----------"

    root=$(find_root)
    echo "ROOT: $root"

    exe=$(realpath --no-symlinks "$root/recipies/$product")
    echo "EXE:  $exe"

    tmp="$root/_working/$product/$(date +%F_%H-%M-%S)"
    mkdir -p "$tmp"
    tmp=$(realpath --no-symlinks "$tmp")
    echo "TMP : $tmp"

    log=$(realpath --no-symlinks "$tmp/main.log")
    echo "LOG:  $log"

    mkdir -p "$tmp" && pushd "$_" 1>/dev/null || exit
    "$exe" | tee "$log"
    popd 1>/dev/null 2>&1
    echo "----------"
}

find_root() {
    dir=$(realpath --no-symlinks "${BASH_SOURCE[0]}")
    dir=$(dirname "$dir")
    until [ -d "$dir/recipies" ]; do
        sub=$(dirname "$dir")
        [ "$dir" != "$sub" ] || exit 1
        dir=$sub
    done
    echo "$dir"
}

main "$@"
read
