#!/usr/bin/env bash

product=$1
sub=$(date +%F_%H-%M-%S)

mkdir -p "../_working/$product/$sub" && pushd "$_" 1>/dev/null || exit
echo "----------"
echo "LOG: $PWD"/main.log
echo "----------"
exe=$(realpath  "../../../recipies/$product")
$exe | tee main.log
popd 1>/dev/null 2>&1

echo "----------"
read
