#!/usr/bin/env bash

main() {
    if [ -z "$1" ]; then
        echo "Usage: build some-product"
        exit 1
    fi

    product=$1
    root=$(find_root)
    exe=$(realpath --no-symlinks "$root/$product")
    tmp="$root/_working/$product/$(date +%F_%H-%M-%S)"
    mkdir -p "$tmp"
    tmp=$(realpath --no-symlinks "$tmp")
    log="$tmp/main.log"

    echo "----------"
    echo "PROD: $exe"
    echo "TEMP: $tmp"
    echo "LOG:  $log"

    mkdir -p "$root" && pushd "$_" 1>/dev/null || exit
      echo "PWD:  $PWD"
      "$exe" | tee "$log"
    popd 1>/dev/null 2>&1
    echo "----------"
}

find_root() {
    dir=$(realpath --no-symlinks "${BASH_SOURCE[0]}")
    dir=$(dirname "$dir")
    until [ -d "$dir/include" ]; do
        sub=$(dirname "$dir")
        [ "$dir" != "$sub" ] || exit 1
        dir=$sub
    done
    echo "$dir"
}

main "$@"
echo "[DONE]"
echo "Press ENTER to exit..."
read
