#!/usr/bin/env bash

CWD="$(pwd)"
ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

echo "(CWD: $CWD)"
echo "(ROOT: $ROOT)"

$ROOT/../delay_short/recipe
$ROOT/../delay_long/recipe
