#!/usr/bin/env bash

echo "BUILD: [START]"

if [ -z "$1" ]; then
    echo "Usage: build some-product"
    exit 1
fi

product=$1
root=$(realpath --no-symlinks "${BASH_SOURCE[0]}")
root=$(dirname "$root")
exe=$(realpath --no-symlinks "$root/recipies/$product")
tmp="$root/_working/$product/$(date +%F_%H-%M-%S)"
mkdir -p "$tmp"
# tmp=$(realpath --no-symlinks "$tmp")
#log="$tmp/main.log"

echo "BUILD: PROD: $exe"
echo "BUILD: TEMP: $tmp"
#echo "BUILD: LOG:  $log"

mkdir -p "$root/recipies" && pushd "$_" 1>/dev/null || exit
echo "BUILD: PWD = $PWD"
  echo "----------"
  "$exe" "$tmp" | tee "$tmp/main.log"
  echo "----------"
popd 1>/dev/null 2>&1

echo "BUILD: [DONE]"
echo "BUILD: Press ENTER to exit..."
read
