#!/usr/bin/env bash

##################################################
# FUNCTIONS

teetime () {
  buffer=
  while IFS= read -r -n1 ch; do
    case $ch in
      '')
        echo     "$buffer"
        echo -ne  "$(date '+%Y-%m-%d %H:%M:%S')\t" >> "$1"
        echo   "$buffer" >> "$1"
        buffer=
        ;;
      $'\r')
        echo -n  "$buffer$ch"
        echo -ne  "$(date '+%Y-%m-%d %H:%M:%S')\t" >> "$1"
        echo   "$buffer" >> "$1"
        buffer=
        ;;
      *)
        buffer=$buffer$ch
        ;;
    esac
  done
}

##################################################
# MAIN

if [ -z "$1" ]; then
    echo "Usage: build some-product"
    exit 1
fi

product=$1
debug=$2
root=$(realpath --no-symlinks "${BASH_SOURCE[0]}")
root=$(dirname "$root")
exe=$(realpath --no-symlinks "$root/recipies/$product.rcpt")

if [ "$debug" == "debug" ]; then
  tmp="$root/_working/$product/_DEBUG"
  rm -fdr "$tmp/_repo"
else
  tmp="$root/_working/$product/$(date '+%Y-%m-%d_%H-%M-%S')"
fi

echo "----------------------------------------"
echo "BUILD: PROD: $exe"
echo "BUILD: TEMP: $tmp"

mkdir -p "$tmp" && pushd "$_" 1>/dev/null || exit
  echo "----------------------------------------"
  "$exe" |& teetime 0000.log
  echo "----------------------------------------"
popd 1>/dev/null 2>&1
