#!/usr/bin/env sh

DIRNAME="${BASH_SOURCE%[/\\]*}"

echo "========================="
echo "DIRNAME=$DIRNAME"
echo "========================="

#source "$DIRNAME/include/bash.sh"

#init
# "$DIRNAME/delay-short"
# "$DIRNAME/delay-long"

echo $PWD

./delay-short
./delay-long
