#!/usr/bin/env sh

DIRNAME="${BASH_SOURCE%[/\\]*}"

echo "========================="
echo DIRNAME=$DIRNAME
echo "========================="

# source $DIRNAME/_lib/include.sh"

init
"$DIRNAME/delay-short"
"$DIRNAME/delay-long"
