#!/usr/bin/env node

const { asleep } = require(`${__dirname}/include/js/sys.js`);

(async () => {
  console.log('WOOD step 1/2');
  await asleep(500);

  console.log('WOOD step 2/2');
  await asleep(500);
})();
